### ISSUE TITLE
Entitas atau Atribut

### ISSUE THREAD

**Issue by syamcode** [MZaidA/Travelendar#7]
Mau bertanya untuk skema database #4 yang telah dibuat. Mengapa start_time, end_time, start_date dan end_date harus dibuat menjadi entitas tersendiri tidak menjadi sebuah atribut?

Terima Kasih

**Comment by nmryn** [comment]
Terimakasi atas koreksinya, akan saya buat start_time, start_date, ... beserta entity departure, arrival menjadi attribute untuk entity schedule, dan entity transportation menjadi attribute dari entity vehicle
